"""
	Even Fibonacci numbers
	Problem 2
	Each new term in the Fibonacci sequence is generated by adding the previous 
	two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not 
	exceed four million, find the sum of the even-valued terms.
"""

def fib(n):
 a,b = 1,2
 for i in range(n-1):
  a,b = b,a+b
 return a

def sum_of_even_fib(limit):
	sum = 0
	n = 0
	i = 1
	while n < limit:
		n = fib(i)
		if n%2 == 0:
			sum += n
		i += 1
	return sum
if __name__ == "__main__":
    print(sum_of_even_fib(4000000))